# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('contact', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
