# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
